<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:include filename="epick_body.xacro"/>
  <xacro:include filename="$(find epick_description)/urdf/epick_driver_ros2_control.xacro" />
  <xacro:macro name="epick_single_suction_cup"
               params="parent
                       origin_xyz:='0 0 0'
                       origin_rpy:='0 0 0'
                       prefix:=''
                       suction_cup_radius:=0.012
                       suction_cup_height:=0.015
                       extension_radius:=0.0
                       extension_length:=0.0
                       tcp_stroke_compensation:=0.0
                       use_fake_hardware:=true
                       usb_port:=/dev/ttyUSB0">

    <xacro:epick_driver_ros2_control
      name="epick_driver_ros2_control"
      use_fake_hardware="${use_fake_hardware}"
      usb_port="${usb_port}"
    />
    <xacro:epick_body parent="${parent}"/>
    <xacro:property name="suction_cup_parent" value="${body_link}"/>
    <xacro:property name="suction_cup_parent_length" value="${body_length}"/>

    <xacro:if value="${extension_length * extension_radius > 0.0}">
        <xacro:property name="suction_cup_parent" value="${prefix}epick_extension"/>
        <xacro:property name="suction_cup_parent_length" value="${extension_length}"/>
        <xacro:cylinder_link name="${prefix}epick_extension"
                             radius="${extension_radius}"
                             length="${extension_length}"
                             color="${body_color}"
                             parent="${body_link}"
                             origin_xyz="0 0 ${(body_length + extension_length) / 2}"/>
    </xacro:if>

    <xacro:cylinder_link name="${prefix}epick_suction_cup"
                         radius="${suction_cup_radius}"
                         length="${suction_cup_height}"
                         color="${body_color}"
                         parent="${suction_cup_parent}"
                         origin_xyz="0 0 ${(suction_cup_parent_length + suction_cup_height) / 2}"/>

    <link name="${prefix}epick_tip">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.0001"/>
        <inertia ixx="1e-8" iyy="1e-8" izz="1e-8" ixy="0" ixz="0" iyz="0"/>
      </inertial>
    </link>

    <xacro:joint parent="${prefix}epick_suction_cup"
                 child="${prefix}epick_tip"
                 xyz="0 0 ${suction_cup_height / 2}"/>

    <link name="${prefix}epick_tcp">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.0001"/>
        <inertia ixx="1e-8" iyy="1e-8" izz="1e-8" ixy="0" ixz="0" iyz="0"/>
      </inertial>
    </link>

    <xacro:joint parent="${prefix}epick_tip"
                 child="${prefix}epick_tcp"
                 xyz="0 0 ${-tcp_stroke_compensation}"/>

    <link name="${prefix}epick_vacuum_state">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.0001"/>
        <inertia ixx="1e-8" iyy="1e-8" izz="1e-8" ixy="0" ixz="0" iyz="0"/>
      </inertial>
    </link>
    
    <joint name="gripper" type="revolute">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <parent link="${prefix}epick_tcp"/>
      <child link="${prefix}epick_vacuum_state"/>
      <limit effort="30" velocity="1.0" lower="0.0" upper="1.0" />
    </joint>
  </xacro:macro>
</robot>
